number_1 = input("Enter the first number: ")
number_2 = input("Enter the second number: ")
result = int(number_1) * int(number_2)
print("the result of multiplication: " + str(result) )
print("the third one")
